# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build assets

on:
    push:
        branches: [ master, 0.x.x ]
    pull_request:
        branches: [ master, 0.x.x ]

jobs:
    build:

        runs-on: ubuntu-18.04

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}

            -   name: Use Node.js 12
                uses: actions/setup-node@v2
                with:
                    node-version: 12

            -   run: npm ci
            -   run: npm test

            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Build assets
